---
- name: Set Falcon defaults
  ansible.builtin.import_playbook: pokerops.crowdstrike.defaults

- name: Verify groups and hosts
  hosts: crowdstrike
  tasks:
    - name: Verify group
      run_once: true
      delegate_to: localhost
      block:
        - name: Get Crowdstrike Authentication Token
          ansible.builtin.uri:
            url: "{{ falcon_api_base }}/oauth2/token"
            follow_redirects: "{{ falcon_api_redirect }}"
            method: POST
            body_format: form-urlencoded
            body:
              client_id: "{{ falcon_client_id }}"
              client_secret: "{{ falcon_client_secret }}"
            status_code: 201
          register: auth_response

        - name: Set auth facts
          set_fact:
            api_token: "{{ auth_response.json.access_token }}"
          no_log: true

        - name: Query registered groups
          ansible.builtin.uri:
            url: "{{ falcon_api_base }}/devices/combined/host-groups/v1?filter={{ _filter }}"
            follow_redirects: "{{ falcon_api_redirect }}"
            method: GET
            headers:
              Authorization: "Bearer {{ api_token }}"
            body_format: form-urlencoded
          vars:
            _filter: "name:'{{ falcon_group }}'"
          register: group_query

        - name: Set group facts
          ansible.builtin.set_fact:
            group_data: "{{ group_query.json.resources }}"

        - name: Verify group facts
          ansible.builtin.assert:
            that:
              - group_data is not none
              - group_data | length == 1
            fail_msg: "Group query returned unexpected results: {{ group_data }}"

    - name: Query agent id
      crowdstrike.falcon.falconctl_info:
        name:
          - "aid"
      register: agent_info_query
      become: true

    - name: Set agent id facts
      ansible.builtin.set_fact:
        agent_id: "{{ agent_info_query.falconctl_info.aid }}"

    - name: Debug agent id
      ansible.builtin.debug:
        var: agent_id

    - name: Verify Falcon agents
      delegate_to: localhost
      block:
        - name: Query registered agents
          ansible.builtin.uri:
            url: "{{ falcon_api_base }}/devices/queries/devices/v1?filter={{ _filter }}&limit={{ falcon_api_page_size }}"
            follow_redirects: "{{ falcon_api_redirect }}"
            method: GET
            headers:
              Authorization: "Bearer {{ api_token }}"
          vars:
            _filter: "hostname:['{{ inventory_hostname }}']"
          register: host_query

        - name: Set agent facts
          ansible.builtin.set_fact:
            falcon_host_data: "{{ host_query.json.resources }}"

        - name: Verify agent facts
          ansible.builtin.assert:
            that:
              - falcon_host_data is not none
              - falcon_host_data | length == 1
            fail_msg: "Host query returned unexpected results: {{ falcon_host_data }}"

        - name: Verify group registrations
          ansible.builtin.uri:
            url: "{{ falcon_api_base }}/devices/queries/host-group-members/v1?id={{ _group.id }}"
            follow_redirects: "{{ falcon_api_redirect }}"
            method: GET
            headers:
              Authorization: "Bearer {{ api_token }}"
          vars:
            _group: "{{ group_data | first }}"
            _group_members: "{{ group_members_query.json.resources | sort }}"
            _agent_ids: "{{ ansible_play_hosts | map('extract', hostvars, 'agent_id') | sort | list }}"
          register: group_members_query
          run_once: true
          until: _agent_ids == _group_members
          retries: 5
          delay: 60
