---
- name: Set Falcon defaults
  ansible.builtin.import_playbook: pokerops.crowdstrike.defaults

- name: Validate Falcon install params
  ansible.builtin.import_playbook: pokerops.crowdstrike.validate

- name: Create Falcon group
  ansible.builtin.import_playbook: pokerops.crowdstrike.group

- name: Deploy Falcon Agent
  ansible.builtin.import_playbook: pokerops.crowdstrike.install
