---
- name: Set Falcon defaults
  ansible.builtin.import_playbook: pokerops.crowdstrike.defaults

- name: Validate Falcon install params
  ansible.builtin.import_playbook: pokerops.crowdstrike.validate

- name: Undeploy Falcon hosts
  ansible.builtin.import_playbook: pokerops.crowdstrike.uninstall

- name: Destroy Falcon group
  ansible.builtin.import_playbook: pokerops.crowdstrike.group
  when: falcon_group_manage | bool
