---
name: libvirt

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        scenario:
          - install
        os:
          - jammy
          - noble
          - bookworm
          - rocky9
    env:
      MOLECULE_LOGDIR: "/tmp/logs"
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            MOLECULE_LOGDIR=${{ env.MOLECULE_LOGDIR }}
            MOLECULE_SCENARIO=${{ matrix.scenario }}
            MOLECULE_KVM_DISTRO=${{ matrix.os }}
            CROWDSTRIKE_CLIENT_ID=${{ secrets.CROWDSTRIKE_CLIENT_ID }}
            CROWDSTRIKE_CLIENT_SECRET=${{ secrets.CROWDSTRIKE_CLIENT_SECRET }}
            devbox run -- make requirements ${{ matrix.os }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.os }}
          path: |
            ${{ env.MOLECULE_LOGDIR }}/*.log
          if-no-files-found: ignore
        if: always()
